using Microsoft.EntityFrameworkCore;
using System;

namespace Varico.EF.Models
{
    public class VaricoDbContext : DbContext
    {
        public VaricoDbContext(DbContextOptions<VaricoDbContext> options) : base(options)
        {
        }

        public DbSet<Users> Users { get; set; }


        public DbSet<Vehicle> Vehicles { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            var cars = new List<Vehicle>
            {
                new Vehicle
                {
                    Id = 1,
                    Brand = "BMW",
                    Model = "Seria 5",
                    ProductionYear = 2020,
                    VehicleType = VehicleType.Passenger,
                    BodyType = BodyType.SEDAN,
                    Availability = true,
                    ReservedById = null,
                    PictureURL = "https://superauto.wpcdn.pl/offer_photos/thumb/767x511_fit_in_27184e1f028225b5d6a8330cad59d18d.jpg",
                    Mileage = 12000,
                    Transmission = TransmissionType.Automatic,
                    EngineCapacity = 2.0,
                    Price = 150000,
                    FuelType = FuelType.Petrol,
                    Drivetrain = DrivetrainType.FWD,
                    Acceleration = 6.5,
                    TrunkCapacity = 480,
                    MaxSpeed = 240
                },
                new Vehicle
                {
                    Id = 2,
                    Brand = "Jaecoo 7",
                    Model = "1.6 T-GDI Urban DCT",
                    ProductionYear = 2015,
                    VehicleType = VehicleType.Passenger,
                    BodyType = BodyType.HATCHBACK,
                    Availability = true,
                    ReservedById = null,
                    PictureURL = "https://superauto.wpcdn.pl/offer_photos/thumb/767x511_fit_in_c8af3789e35cfe931acb4dc341a879d8.jpg",
                    Mileage = 75000,
                    Transmission = TransmissionType.Manual,
                    EngineCapacity = 1.6,
                    Price = 45000,
                    FuelType = FuelType.Diesel,
                    Drivetrain = DrivetrainType.FWD,
                    Acceleration = 9.2,
                    TrunkCapacity = 370,
                    MaxSpeed = 210
                },
                new Vehicle
                {
                    Id = 3,
                    Brand = "MG 3",
                    Model = "A3",
                    ProductionYear = 2024,
                    VehicleType = VehicleType.Passenger,
                    BodyType = BodyType.HATCHBACK,
                    Availability = true,
                    ReservedById = null,
                    PictureURL = "https://www.superauto.pl/file/2611717/3bbd42a17213074b29b6018891029b448b4a8aff-2-767x511",
                    Mileage = 0,
                    Transmission = TransmissionType.Automatic,
                    EngineCapacity = 1.5,
                    Price = 120000,
                    FuelType = FuelType.Petrol,
                    Drivetrain = DrivetrainType.FWD,
                    Acceleration = 7.0,
                    TrunkCapacity = 300,
                    MaxSpeed = 220
                },
                new Vehicle
                {
                    Id = 4,
                    Brand = "Renault Trafic",
                    Model = "Kombi L2H1",
                    ProductionYear = 2025,
                    VehicleType = VehicleType.Passenger,
                    BodyType = BodyType.KOMBI,
                    Availability = true,
                    ReservedById = null,
                    PictureURL = "https://www.superauto.pl/file/2611717/3bbd42a17213074b29b6018891029b448b4a8aff-2-767x511",
                    Mileage = 15000,
                    Transmission = TransmissionType.Manual,
                    EngineCapacity = 2.3,
                    Price = 220000,
                    FuelType = FuelType.Diesel,
                    Drivetrain = DrivetrainType.RWD,
                    Acceleration = 9.5,
                    TrunkCapacity = 1200,
                    MaxSpeed = 190
                },
                new Vehicle
                {
                    Id = 5,
                    Brand = "Mercedes GLC",
                    Model = "300 e 4-Matic AMG Line",
                    ProductionYear = 2025,
                    VehicleType = VehicleType.Passenger,
                    BodyType = BodyType.SUV,
                    Availability = true,
                    ReservedById = null,
                    PictureURL = "https://www.superauto.pl/file/2610911/7ac4af13e602fb674531f7a8580ea8899e02f1e0-2-767x511",
                    Mileage = 0,
                    Transmission = TransmissionType.Automatic,
                    EngineCapacity = 2.0,
                    Price = 250000,
                    FuelType = FuelType.Petrol,
                    Drivetrain = DrivetrainType.AWD,
                    Acceleration = 6.0,
                    TrunkCapacity = 550,
                    MaxSpeed = 240
                },
                new Vehicle
                {
                    Id = 6,
                    Brand = "Ford Kuga",
                    Model = "2.5 FHEV FWD Titanium",
                    ProductionYear = 2024,
                    VehicleType = VehicleType.Passenger,
                    BodyType = BodyType.SEDAN,
                    Availability = true,
                    ReservedById = null,
                    PictureURL = "https://www.superauto.pl/file/2415504/5f0f81a650763a1f3b22267f36c7a8f6bb52d1bb-2-767x511",
                    Mileage = 5000,
                    Transmission = TransmissionType.Automatic,
                    EngineCapacity = 2.5,
                    Price = 180000,
                    FuelType = FuelType.Hybrid,
                    Drivetrain = DrivetrainType.FWD,
                    Acceleration = 7.8,
                    TrunkCapacity = 450,
                    MaxSpeed = 200
                },
                new Vehicle
                {
                    Id = 7,
                    Brand = "Hyundai I30",
                    Model = "1.0 T-GDI Smart",
                    ProductionYear = 2019,
                    VehicleType = VehicleType.Passenger,
                    BodyType = BodyType.KOMBI,
                    Availability = true,
                    ReservedById = null,
                    PictureURL = "https://www.superauto.pl/file/2582987/ccd85d30c20bf1eae1f47a1e8ba097e40dde6524-2-767x511",
                    Mileage = 65000,
                    Transmission = TransmissionType.Manual,
                    EngineCapacity = 1.0,
                    Price = 47000,
                    FuelType = FuelType.Petrol,
                    Drivetrain = DrivetrainType.FWD,
                    Acceleration = 9.9,
                    TrunkCapacity = 370,
                    MaxSpeed = 205
                },
                new Vehicle
                {
                    Id = 8,
                    Brand = "CBR1000RR-R Fireblade",
                    Model = " SP 2024 (model 2024)",
                    ProductionYear = 2024,
                    VehicleType = VehicleType.Motorcycle,
                    BodyType = BodyType.ANOTHER,
                    Availability = true,
                    ReservedById = null,
                    PictureURL = "https://www.honda.pl/content/dam/central/motorcycles/colour-picker/supersports/cbr1000rr-r/cbr1000rr-r_sp_2024/r-380_grandprixred/24YM_CBR1000RR-R_FIREBLADE_Studio_GRAND_PRIX_RED_SP_RHS.png/jcr:content/renditions/fb_r_w.webp",
                    Mileage = 5000,
                    Transmission = TransmissionType.Manual,
                    EngineCapacity = 1.0,
                    Price = 23000,
                    FuelType = FuelType.Petrol,
                    Drivetrain = DrivetrainType.FWD,
                    Acceleration = 2.8,
                    TrunkCapacity = 30,
                    MaxSpeed = 300
                },
                new Vehicle
                {
                    Id = 9,
                    Brand = "CBR1000RR-R Fireblade",
                    Model = " SP Carbon Edition",
                    ProductionYear = 2025,
                    VehicleType = VehicleType.Motorcycle,
                    BodyType = BodyType.ANOTHER,
                    Availability = true,
                    ReservedById = null,
                    PictureURL = "https://www.honda.pl/content/dam/central/motorcycles/colour-picker/supersports/cbr1000rr-r/cbr1000rr-r_sp_carbon_2024/nh-c33p_mattepearlmorionblack/24YM_CBR1000RR-R_FIREBLADE_Studio_MAT_PEARL_MORION_BLACK_SP_Carbon_Edition_RHS.png/jcr:content/renditions/fb_r_w.webp",
                    Mileage = 3500,
                    Transmission = TransmissionType.Manual,
                    EngineCapacity = 1.0,
                    Price = 25000,
                    FuelType = FuelType.Petrol,
                    Drivetrain = DrivetrainType.FWD,
                    Acceleration = 2.6,
                    TrunkCapacity = 30,
                    MaxSpeed = 310
                },
                new Vehicle
                {
                    Id = 10,
                    Brand = "CBR1000RR-R Fireblade",
                    Model = " SP Carbon Edition",
                    ProductionYear = 2025,
                    VehicleType = VehicleType.Motorcycle,
                    BodyType = BodyType.ANOTHER,
                    Availability = true,
                    ReservedById = null,
                    PictureURL = "https://www.honda.pl/content/dam/central/motorcycles/colour-picker/supersports/cbr1000rr-r/cbr1000rr-r_sp_carbon_2024/nh-c33p_mattepearlmorionblack/24YM_CBR1000RR-R_FIREBLADE_Studio_MAT_PEARL_MORION_BLACK_SP_Carbon_Edition_RHS.png/jcr:content/renditions/fb_r_w.webp",
                    Mileage = 100,
                    Transmission = TransmissionType.Manual,
                    EngineCapacity = 2.0,
                    Price = 25000,
                    FuelType = FuelType.Gas,
                    Drivetrain = DrivetrainType.FWD,
                    Acceleration = 2.6,
                    TrunkCapacity = 45,
                    MaxSpeed = 450
                },
                new Vehicle
                {
                    Id = 11,
                    Brand = "Toyota",
                    Model = "Corolla",
                    ProductionYear = 2023,
                    VehicleType = VehicleType.Passenger,
                    BodyType = BodyType.SEDAN,
                    Availability = true,
                    ReservedById = null,
                    PictureURL = "https://www.superauto.pl/file/2611717/3bbd42a17213074b29b6018891029b448b4a8aff-2-767x511",
                    Mileage = 10000,
                    Transmission = TransmissionType.Automatic,
                    EngineCapacity = 1.8,
                    Price = 90000,
                    FuelType = FuelType.Hybrid,
                    Drivetrain = DrivetrainType.FWD,
                    Acceleration = 8.2,
                    TrunkCapacity = 470,
                    MaxSpeed = 200
                },
                new Vehicle
                {
                    Id = 12,
                    Brand = "Volkswagen",
                    Model = "Golf",
                    ProductionYear = 2022,
                    VehicleType = VehicleType.Passenger,
                    BodyType = BodyType.HATCHBACK,
                    Availability = true,
                    ReservedById = null,
                    PictureURL = "https://www.superauto.pl/file/2611717/3bbd42a17213074b29b6018891029b448b4a8aff-2-767x511",
                    Mileage = 20000,
                    Transmission = TransmissionType.Manual,
                    EngineCapacity = 1.5,
                    Price = 80000,
                    FuelType = FuelType.Petrol,
                    Drivetrain = DrivetrainType.FWD,
                    Acceleration = 9.0,
                    TrunkCapacity = 380,
                    MaxSpeed = 210
                },
                new Vehicle
                {
                    Id = 13,
                    Brand = "Audi",
                    Model = "A4",
                    ProductionYear = 2021,
                    VehicleType = VehicleType.Passenger,
                    BodyType = BodyType.SEDAN,
                    Availability = true,
                    ReservedById = null,
                    PictureURL = "https://www.superauto.pl/file/2611717/3bbd42a17213074b29b6018891029b448b4a8aff-2-767x511",
                    Mileage = 15000,
                    Transmission = TransmissionType.Automatic,
                    EngineCapacity = 2.0,
                    Price = 170000,
                    FuelType = FuelType.Diesel,
                    Drivetrain = DrivetrainType.AWD,
                    Acceleration = 7.5,
                    TrunkCapacity = 480,
                    MaxSpeed = 240
                },
                new Vehicle
                {
                    Id = 14,
                    Brand = "Skoda",
                    Model = "Octavia",
                    ProductionYear = 2024,
                    VehicleType = VehicleType.Passenger,
                    BodyType = BodyType.KOMBI,
                    Availability = true,
                    ReservedById = null,
                    PictureURL = "https://www.superauto.pl/file/2611717/3bbd42a17213074b29b6018891029b448b4a8aff-2-767x511",
                    Mileage = 5000,
                    Transmission = TransmissionType.Automatic,
                    EngineCapacity = 1.6,
                    Price = 95000,
                    FuelType = FuelType.Petrol,
                    Drivetrain = DrivetrainType.FWD,
                    Acceleration = 8.8,
                    TrunkCapacity = 600,
                    MaxSpeed = 220
                },
                new Vehicle
                {
                    Id = 15,
                    Brand = "Peugeot",
                    Model = "308",
                    ProductionYear = 2023,
                    VehicleType = VehicleType.Passenger,
                    BodyType = BodyType.HATCHBACK,
                    Availability = true,
                    ReservedById = null,
                    PictureURL = "https://www.superauto.pl/file/2611717/3bbd42a17213074b29b6018891029b448b4a8aff-2-767x511",
                    Mileage = 12000,
                    Transmission = TransmissionType.Manual,
                    EngineCapacity = 1.2,
                    Price = 70000,
                    FuelType = FuelType.Petrol,
                    Drivetrain = DrivetrainType.FWD,
                    Acceleration = 9.5,
                    TrunkCapacity = 340,
                    MaxSpeed = 205
                },
                new Vehicle
                {
                    Id = 16,
                    Brand = "Kia",
                    Model = "Sportage",
                    ProductionYear = 2024,
                    VehicleType = VehicleType.Passenger,
                    BodyType = BodyType.SUV,
                    Availability = true,
                    ReservedById = null,
                    PictureURL = "https://www.superauto.pl/file/2611717/3bbd42a17213074b29b6018891029b448b4a8aff-2-767x511",
                    Mileage = 8000,
                    Transmission = TransmissionType.Automatic,
                    EngineCapacity = 1.6,
                    Price = 130000,
                    FuelType = FuelType.Diesel,
                    Drivetrain = DrivetrainType.AWD,
                    Acceleration = 9.0,
                    TrunkCapacity = 520,
                    MaxSpeed = 210
                },
                new Vehicle
                {
                    Id = 17,
                    Brand = "Volvo",
                    Model = "XC60",
                    ProductionYear = 2025,
                    VehicleType = VehicleType.Passenger,
                    BodyType = BodyType.SUV,
                    Availability = true,
                    ReservedById = null,
                    PictureURL = "https://www.superauto.pl/file/2611717/3bbd42a17213074b29b6018891029b448b4a8aff-2-767x511",
                    Mileage = 0,
                    Transmission = TransmissionType.Automatic,
                    EngineCapacity = 2.0,
                    Price = 240000,
                    FuelType = FuelType.Petrol,
                    Drivetrain = DrivetrainType.AWD,
                    Acceleration = 6.8,
                    TrunkCapacity = 505,
                    MaxSpeed = 230
                },
                new Vehicle
                {
                    Id = 18,
                    Brand = "Mazda",
                    Model = "CX-5",
                    ProductionYear = 2023,
                    VehicleType = VehicleType.Passenger,
                    BodyType = BodyType.SUV,
                    Availability = true,
                    ReservedById = null,
                    PictureURL = "https://www.superauto.pl/file/2611717/3bbd42a17213074b29b6018891029b448b4a8aff-2-767x511",
                    Mileage = 10000,
                    Transmission = TransmissionType.Automatic,
                    EngineCapacity = 2.5,
                    Price = 140000,
                    FuelType = FuelType.Petrol,
                    Drivetrain = DrivetrainType.AWD,
                    Acceleration = 8.2,
                    TrunkCapacity = 510,
                    MaxSpeed = 220
                },
                new Vehicle
                {
                    Id = 19,
                    Brand = "Nissan",
                    Model = "Qashqai",
                    ProductionYear = 2024,
                    VehicleType = VehicleType.Passenger,
                    BodyType = BodyType.SUV,
                    Availability = true,
                    ReservedById = null,
                    PictureURL = "https://www.superauto.pl/file/2611717/3bbd42a17213074b29b6018891029b448b4a8aff-2-767x511",
                    Mileage = 5000,
                    Transmission = TransmissionType.Automatic,
                    EngineCapacity = 1.3,
                    Price = 110000,
                    FuelType = FuelType.Petrol,
                    Drivetrain = DrivetrainType.FWD,
                    Acceleration = 9.5,
                    TrunkCapacity = 430,
                    MaxSpeed = 210
                },
                new Vehicle
                {
                    Id = 20,
                    Brand = "Hyundai",
                    Model = "Tucson",
                    ProductionYear = 2025,
                    VehicleType = VehicleType.Passenger,
                    BodyType = BodyType.SUV,
                    Availability = true,
                    ReservedById = null,
                    PictureURL = "https://www.superauto.pl/file/2611717/3bbd42a17213074b29b6018891029b448b4a8aff-2-767x511",
                    Mileage = 0,
                    Transmission = TransmissionType.Automatic,
                    EngineCapacity = 1.6,
                    Price = 150000,
                    FuelType = FuelType.Hybrid,
                    Drivetrain = DrivetrainType.AWD,
                    Acceleration = 8.5,
                    TrunkCapacity = 540,
                    MaxSpeed = 220
                },
                new Vehicle
                {
                    Id = 21,
                    Brand = "Ford",
                    Model = "Mustang",
                    ProductionYear = 2024,
                    VehicleType = VehicleType.Passenger,
                    BodyType = BodyType.KOMBI,
                    Availability = true,
                    ReservedById = null,
                    PictureURL = "https://www.superauto.pl/file/2611717/3bbd42a17213074b29b6018891029b448b4a8aff-2-767x511",
                    Mileage = 0,
                    Transmission = TransmissionType.Automatic,
                    EngineCapacity = 5.0,
                    Price = 300000,
                    FuelType = FuelType.Petrol,
                    Drivetrain = DrivetrainType.RWD,
                    Acceleration = 4.5,
                    TrunkCapacity = 380,
                    MaxSpeed = 250
                },
                new Vehicle
                {
                    Id = 22,
                    Brand = "Chevrolet",
                    Model = "Camaro",
                    ProductionYear = 2023,
                    VehicleType = VehicleType.Passenger,
                    BodyType = BodyType.HATCHBACK,
                    Availability = true,
                    ReservedById = null,
                    PictureURL = "https://www.superauto.pl/file/2611717/3bbd42a17213074b29b6018891029b448b4a8aff-2-767x511",
                    Mileage = 5000,
                    Transmission = TransmissionType.Automatic,
                    EngineCapacity = 6.2,
                    Price = 280000,
                    FuelType = FuelType.Petrol,
                    Drivetrain = DrivetrainType.RWD,
                    Acceleration = 4.2,
                    TrunkCapacity = 340,
                    MaxSpeed = 260
                },
                new Vehicle
                {
                    Id = 23,
                    Brand = "Tesla",
                    Model = "Model 3",
                    ProductionYear = 2024,
                    VehicleType = VehicleType.Passenger,
                    BodyType = BodyType.SEDAN,
                    Availability = true,
                    ReservedById = null,
                    PictureURL = "https://www.superauto.pl/file/2611717/3bbd42a17213074b29b6018891029b448b4a8aff-2-767x511",
                    Mileage = 0,
                    Transmission = TransmissionType.Automatic,
                    EngineCapacity = 0, // Elektryczny
                    Price = 220000,
                    FuelType = FuelType.Electric,
                    Drivetrain = DrivetrainType.AWD,
                    Acceleration = 3.1,
                    TrunkCapacity = 425,
                    MaxSpeed = 260
                },
                new Vehicle
                {
                    Id = 24,
                    Brand = "Porsche",
                    Model = "911",
                    ProductionYear = 2025,
                    VehicleType = VehicleType.Passenger,
                    BodyType = BodyType.HATCHBACK,
                    Availability = true,
                    ReservedById = null,
                    PictureURL = "https://www.superauto.pl/file/2611717/3bbd42a17213074b29b6018891029b448b4a8aff-2-767x511",
                    Mileage = 0,
                    Transmission = TransmissionType.Automatic,
                    EngineCapacity = 3.0,
                    Price = 500000,
                    FuelType = FuelType.Petrol,
                    Drivetrain = DrivetrainType.RWD,
                    Acceleration = 3.5,
                    TrunkCapacity = 280,
                    MaxSpeed = 300
                },
                new Vehicle
                {
                    Id = 25,
                    Brand = "Fiat",
                    Model = "500",
                    ProductionYear = 2023,
                    VehicleType = VehicleType.Passenger,
                    BodyType = BodyType.HATCHBACK,
                    Availability = true,
                    ReservedById = null,
                    PictureURL = "https://www.superauto.pl/file/2611717/3bbd42a17213074b29b6018891029b448b4a8aff-2-767x511",
                    Mileage = 15000,
                    Transmission = TransmissionType.Manual,
                    EngineCapacity = 1.2,
                    Price = 60000,
                    FuelType = FuelType.Petrol,
                    Drivetrain = DrivetrainType.FWD,
                    Acceleration = 12.0,
                    TrunkCapacity = 185,
                    MaxSpeed = 180
                },
                new Vehicle
                {
                    Id = 26,
                    Brand = "Jeep",
                    Model = "Wrangler",
                    ProductionYear = 2024,
                    VehicleType = VehicleType.Passenger,
                    BodyType = BodyType.SUV,
                    Availability = true,
                    ReservedById = null,
                    PictureURL = "https://www.superauto.pl/file/2611717/3bbd42a17213074b29b6018891029b448b4a8aff-2-767x511",
                    Mileage = 0,
                    Transmission = TransmissionType.Automatic,
                    EngineCapacity = 2.0,
                    Price = 200000,
                    FuelType = FuelType.Petrol,
                    Drivetrain = DrivetrainType.AWD,
                    Acceleration = 8.0,
                    TrunkCapacity = 270,
                    MaxSpeed = 200
                },
                new Vehicle
                {
                    Id = 27,
                    Brand = "Land Rover",
                    Model = "Defender",
                    ProductionYear = 2025,
                    VehicleType = VehicleType.Passenger,
                    BodyType = BodyType.SUV,
                    Availability = true,
                    ReservedById = null,
                    PictureURL = "https://www.superauto.pl/file/2611717/3bbd42a17213074b29b6018891029b448b4a8aff-2-767x511",
                    Mileage = 0,
                    Transmission = TransmissionType.Automatic,
                    EngineCapacity = 3.0,
                    Price = 350000,
                    FuelType = FuelType.Diesel,
                    Drivetrain = DrivetrainType.AWD,
                    Acceleration = 6.5,
                    TrunkCapacity = 550,
                    MaxSpeed = 220
                },
                new Vehicle
                {
                    Id = 28,
                    Brand = "Subaru",
                    Model = "Outback",
                    ProductionYear = 2024,
                    VehicleType = VehicleType.Passenger,
                    BodyType = BodyType.KOMBI,
                    Availability = true,
                    ReservedById = null,
                    PictureURL = "https://www.superauto.pl/file/2611717/3bbd42a17213074b29b6018891029b448b4a8aff-2-767x511",
                    Mileage = 5000,
                    Transmission = TransmissionType.Automatic,
                    EngineCapacity = 2.5,
                    Price = 160000,
                    FuelType = FuelType.Petrol,
                    Drivetrain = DrivetrainType.AWD,
                    Acceleration = 8.0,
                    TrunkCapacity = 580,
                    MaxSpeed = 210
                },
                new Vehicle
                {
                    Id = 29,
                    Brand = "Lexus",
                    Model = "RX",
                    ProductionYear = 2025,
                    VehicleType = VehicleType.Passenger,
                    BodyType = BodyType.SUV,
                    Availability = true,
                    ReservedById = null,
                    PictureURL = "https://www.superauto.pl/file/2611717/3bbd42a17213074b29b6018891029b448b4a8aff-2-767x511",
                    Mileage = 0,
                    Transmission = TransmissionType.Automatic,
                    EngineCapacity = 3.5,
                    Price = 300000,
                    FuelType = FuelType.Hybrid,
                    Drivetrain = DrivetrainType.AWD,
                    Acceleration = 7.0,
                    TrunkCapacity = 520,
                    MaxSpeed = 230
                },
                new Vehicle
                {
                    Id = 30,
                    Brand = "Honda",
                    Model = "Civic",
                    ProductionYear = 2024,
                    VehicleType = VehicleType.Passenger,
                    BodyType = BodyType.SEDAN,
                    Availability = true,
                    ReservedById = null,
                    PictureURL = "https://www.superauto.pl/file/2611717/3bbd42a17213074b29b6018891029b448b4a8aff-2-767x511",
                    Mileage = 0,
                    Transmission = TransmissionType.Automatic,
                    EngineCapacity = 1.5,
                    Price = 100000,
                    FuelType = FuelType.Petrol,
                    Drivetrain = DrivetrainType.FWD,
                    Acceleration = 8.0,
                    TrunkCapacity = 420,
                    MaxSpeed = 210
                }
            };
            modelBuilder.Entity<Vehicle>().HasData(cars);
            modelBuilder.Entity<Vehicle>()
                .HasOne(c => c.ReservedBy)
                .WithMany()
                .HasForeignKey(c => c.ReservedById);

            base.OnModelCreating(modelBuilder);
        }
    }
}