// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Varico.EF.Models;

#nullable disable

namespace Varico.EF.Migrations
{
    [DbContext(typeof(VaricoDbContext))]
    [Migration("20250220220539_AddedNullableToPropertyInVehicles")]
    partial class AddedNullableToPropertyInVehicles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Varico.EF.Models.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CarId")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Varico.EF.Models.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Availability")
                        .HasColumnType("bit");

                    b.Property<int>("BodyType")
                        .HasColumnType("int");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PictureURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductionYear")
                        .HasColumnType("int");

                    b.Property<int?>("ReservedById")
                        .HasColumnType("int");

                    b.Property<int>("VehicleType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReservedById");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Availability = true,
                            BodyType = 2,
                            Brand = "BMW",
                            Model = "Seria 5",
                            PictureURL = "https://superauto.wpcdn.pl/offer_photos/thumb/767x511_fit_in_27184e1f028225b5d6a8330cad59d18d.jpg",
                            ProductionYear = 2020,
                            ReservedById = 0,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = 2,
                            Availability = true,
                            BodyType = 1,
                            Brand = "Jaecoo 7",
                            Model = "1.6 T-GDI Urban DCT",
                            PictureURL = "https://superauto.wpcdn.pl/offer_photos/thumb/767x511_fit_in_c8af3789e35cfe931acb4dc341a879d8.jpg",
                            ProductionYear = 2015,
                            ReservedById = 0,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = 3,
                            Availability = true,
                            BodyType = 1,
                            Brand = "MG 3",
                            Model = "A3",
                            PictureURL = "https://www.superauto.pl/file/2611717/3bbd42a17213074b29b6018891029b448b4a8aff-2-767x511",
                            ProductionYear = 2024,
                            ReservedById = 0,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = 4,
                            Availability = true,
                            BodyType = 3,
                            Brand = "Renault Trafic",
                            Model = "Kombi L2H1",
                            PictureURL = "https://www.superauto.pl/file/2611717/3bbd42a17213074b29b6018891029b448b4a8aff-2-767x511",
                            ProductionYear = 2025,
                            ReservedById = 0,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = 5,
                            Availability = true,
                            BodyType = 0,
                            Brand = "Mercedes GLC",
                            Model = "300 e 4-Matic AMG Line",
                            PictureURL = "https://www.superauto.pl/file/2610911/7ac4af13e602fb674531f7a8580ea8899e02f1e0-2-767x511",
                            ProductionYear = 2025,
                            ReservedById = 0,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = 6,
                            Availability = true,
                            BodyType = 2,
                            Brand = "Ford Kuga",
                            Model = "2.5 FHEV FWD Titanium",
                            PictureURL = "https://www.superauto.pl/file/2415504/5f0f81a650763a1f3b22267f36c7a8f6bb52d1bb-2-767x511",
                            ProductionYear = 2024,
                            ReservedById = 0,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = 7,
                            Availability = true,
                            BodyType = 3,
                            Brand = "Hyundai I30",
                            Model = "1.0 T-GDI Smart",
                            PictureURL = "https://www.superauto.pl/file/2582987/ccd85d30c20bf1eae1f47a1e8ba097e40dde6524-2-767x511",
                            ProductionYear = 2019,
                            ReservedById = 0,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = 8,
                            Availability = true,
                            BodyType = 4,
                            Brand = "CBR1000RR-R Fireblade",
                            Model = " SP 2024 (model 2024)",
                            PictureURL = "https://www.honda.pl/content/dam/central/motorcycles/colour-picker/supersports/cbr1000rr-r/cbr1000rr-r_sp_2024/r-380_grandprixred/24YM_CBR1000RR-R_FIREBLADE_Studio_GRAND_PRIX_RED_SP_RHS.png/jcr:content/renditions/fb_r_w.webp",
                            ProductionYear = 2024,
                            ReservedById = 0,
                            VehicleType = 2
                        },
                        new
                        {
                            Id = 9,
                            Availability = true,
                            BodyType = 4,
                            Brand = "CBR1000RR-R Fireblade",
                            Model = " SP Carbon Edition",
                            PictureURL = "https://www.honda.pl/content/dam/central/motorcycles/colour-picker/supersports/cbr1000rr-r/cbr1000rr-r_sp_carbon_2024/nh-c33p_mattepearlmorionblack/24YM_CBR1000RR-R_FIREBLADE_Studio_MAT_PEARL_MORION_BLACK_SP_Carbon_Edition_RHS.png/jcr:content/renditions/fb_r_w.webp",
                            ProductionYear = 2025,
                            ReservedById = 0,
                            VehicleType = 2
                        },
                        new
                        {
                            Id = 10,
                            Availability = true,
                            BodyType = 4,
                            Brand = "CRF450R",
                            Model = "2025",
                            PictureURL = "https://www.honda.pl/content/dam/central/motorcycles/colour-picker/off-road/crf450r/crf450r_2023/r-292r_extreme_red/crf450r_2023_r-292r_extreme_red.png/jcr:content/renditions/fb_r_w.webp",
                            ProductionYear = 2025,
                            ReservedById = 0,
                            VehicleType = 2
                        },
                        new
                        {
                            Id = 11,
                            Availability = true,
                            BodyType = 4,
                            Brand = "CRF450R",
                            Model = "2024",
                            PictureURL = "https://www.honda.pl/content/dam/central/motorcycles/colour-picker/off-road/crf450r/crf450r_2023/r-292r_extreme_red/crf450r_2023_r-292r_extreme_red.png/jcr:content/renditions/fb_r_w.webp",
                            ProductionYear = 2025,
                            ReservedById = 0,
                            VehicleType = 2
                        });
                });

            modelBuilder.Entity("Varico.EF.Models.Users", b =>
                {
                    b.HasOne("Varico.EF.Models.Vehicle", "Car")
                        .WithMany()
                        .HasForeignKey("CarId");

                    b.Navigation("Car");
                });

            modelBuilder.Entity("Varico.EF.Models.Vehicle", b =>
                {
                    b.HasOne("Varico.EF.Models.Users", "ReservedBy")
                        .WithMany()
                        .HasForeignKey("ReservedById");

                    b.Navigation("ReservedBy");
                });
#pragma warning restore 612, 618
        }
    }
}
