// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Varico.EF.Models;

#nullable disable

namespace Varico.EF.Migrations
{
    [DbContext(typeof(VaricoDbContext))]
    [Migration("20250221032113_AddedReservationTime")]
    partial class AddedReservationTime
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Varico.EF.Models.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CarId")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Varico.EF.Models.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Acceleration")
                        .HasColumnType("float");

                    b.Property<bool>("Availability")
                        .HasColumnType("bit");

                    b.Property<int>("BodyType")
                        .HasColumnType("int");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly?>("DateEnd")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DateStart")
                        .HasColumnType("date");

                    b.Property<int>("Drivetrain")
                        .HasColumnType("int");

                    b.Property<double>("EngineCapacity")
                        .HasColumnType("float");

                    b.Property<int>("FuelType")
                        .HasColumnType("int");

                    b.Property<double>("MaxSpeed")
                        .HasColumnType("float");

                    b.Property<double>("Mileage")
                        .HasColumnType("float");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PictureURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductionYear")
                        .HasColumnType("int");

                    b.Property<int?>("ReservedById")
                        .HasColumnType("int");

                    b.Property<int>("Transmission")
                        .HasColumnType("int");

                    b.Property<double>("TrunkCapacity")
                        .HasColumnType("float");

                    b.Property<int>("VehicleType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReservedById");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Acceleration = 6.5,
                            Availability = true,
                            BodyType = 2,
                            Brand = "BMW",
                            Drivetrain = 0,
                            EngineCapacity = 2.0,
                            FuelType = 0,
                            MaxSpeed = 240.0,
                            Mileage = 12000.0,
                            Model = "Seria 5",
                            PictureURL = "https://superauto.wpcdn.pl/offer_photos/thumb/767x511_fit_in_27184e1f028225b5d6a8330cad59d18d.jpg",
                            Price = 150000m,
                            ProductionYear = 2020,
                            Transmission = 1,
                            TrunkCapacity = 480.0,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = 2,
                            Acceleration = 9.1999999999999993,
                            Availability = true,
                            BodyType = 1,
                            Brand = "Jaecoo 7",
                            Drivetrain = 0,
                            EngineCapacity = 1.6000000000000001,
                            FuelType = 1,
                            MaxSpeed = 210.0,
                            Mileage = 75000.0,
                            Model = "1.6 T-GDI Urban DCT",
                            PictureURL = "https://superauto.wpcdn.pl/offer_photos/thumb/767x511_fit_in_c8af3789e35cfe931acb4dc341a879d8.jpg",
                            Price = 45000m,
                            ProductionYear = 2015,
                            Transmission = 0,
                            TrunkCapacity = 370.0,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = 3,
                            Acceleration = 7.0,
                            Availability = true,
                            BodyType = 1,
                            Brand = "MG 3",
                            Drivetrain = 0,
                            EngineCapacity = 1.5,
                            FuelType = 0,
                            MaxSpeed = 220.0,
                            Mileage = 0.0,
                            Model = "A3",
                            PictureURL = "https://www.superauto.pl/file/2611717/3bbd42a17213074b29b6018891029b448b4a8aff-2-767x511",
                            Price = 120000m,
                            ProductionYear = 2024,
                            Transmission = 1,
                            TrunkCapacity = 300.0,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = 4,
                            Acceleration = 9.5,
                            Availability = true,
                            BodyType = 3,
                            Brand = "Renault Trafic",
                            Drivetrain = 1,
                            EngineCapacity = 2.2999999999999998,
                            FuelType = 1,
                            MaxSpeed = 190.0,
                            Mileage = 15000.0,
                            Model = "Kombi L2H1",
                            PictureURL = "https://www.superauto.pl/file/2611717/3bbd42a17213074b29b6018891029b448b4a8aff-2-767x511",
                            Price = 220000m,
                            ProductionYear = 2025,
                            Transmission = 0,
                            TrunkCapacity = 1200.0,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = 5,
                            Acceleration = 6.0,
                            Availability = true,
                            BodyType = 0,
                            Brand = "Mercedes GLC",
                            Drivetrain = 2,
                            EngineCapacity = 2.0,
                            FuelType = 0,
                            MaxSpeed = 240.0,
                            Mileage = 0.0,
                            Model = "300 e 4-Matic AMG Line",
                            PictureURL = "https://www.superauto.pl/file/2610911/7ac4af13e602fb674531f7a8580ea8899e02f1e0-2-767x511",
                            Price = 250000m,
                            ProductionYear = 2025,
                            Transmission = 1,
                            TrunkCapacity = 550.0,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = 6,
                            Acceleration = 7.7999999999999998,
                            Availability = true,
                            BodyType = 2,
                            Brand = "Ford Kuga",
                            Drivetrain = 0,
                            EngineCapacity = 2.5,
                            FuelType = 3,
                            MaxSpeed = 200.0,
                            Mileage = 5000.0,
                            Model = "2.5 FHEV FWD Titanium",
                            PictureURL = "https://www.superauto.pl/file/2415504/5f0f81a650763a1f3b22267f36c7a8f6bb52d1bb-2-767x511",
                            Price = 180000m,
                            ProductionYear = 2024,
                            Transmission = 1,
                            TrunkCapacity = 450.0,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = 7,
                            Acceleration = 9.9000000000000004,
                            Availability = true,
                            BodyType = 3,
                            Brand = "Hyundai I30",
                            Drivetrain = 0,
                            EngineCapacity = 1.0,
                            FuelType = 0,
                            MaxSpeed = 205.0,
                            Mileage = 65000.0,
                            Model = "1.0 T-GDI Smart",
                            PictureURL = "https://www.superauto.pl/file/2582987/ccd85d30c20bf1eae1f47a1e8ba097e40dde6524-2-767x511",
                            Price = 47000m,
                            ProductionYear = 2019,
                            Transmission = 0,
                            TrunkCapacity = 370.0,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = 8,
                            Acceleration = 2.7999999999999998,
                            Availability = true,
                            BodyType = 4,
                            Brand = "CBR1000RR-R Fireblade",
                            Drivetrain = 0,
                            EngineCapacity = 1.0,
                            FuelType = 0,
                            MaxSpeed = 300.0,
                            Mileage = 5000.0,
                            Model = " SP 2024 (model 2024)",
                            PictureURL = "https://www.honda.pl/content/dam/central/motorcycles/colour-picker/supersports/cbr1000rr-r/cbr1000rr-r_sp_2024/r-380_grandprixred/24YM_CBR1000RR-R_FIREBLADE_Studio_GRAND_PRIX_RED_SP_RHS.png/jcr:content/renditions/fb_r_w.webp",
                            Price = 23000m,
                            ProductionYear = 2024,
                            Transmission = 0,
                            TrunkCapacity = 30.0,
                            VehicleType = 2
                        },
                        new
                        {
                            Id = 9,
                            Acceleration = 2.6000000000000001,
                            Availability = true,
                            BodyType = 4,
                            Brand = "CBR1000RR-R Fireblade",
                            Drivetrain = 0,
                            EngineCapacity = 1.0,
                            FuelType = 0,
                            MaxSpeed = 310.0,
                            Mileage = 3500.0,
                            Model = " SP Carbon Edition",
                            PictureURL = "https://www.honda.pl/content/dam/central/motorcycles/colour-picker/supersports/cbr1000rr-r/cbr1000rr-r_sp_carbon_2024/nh-c33p_mattepearlmorionblack/24YM_CBR1000RR-R_FIREBLADE_Studio_MAT_PEARL_MORION_BLACK_SP_Carbon_Edition_RHS.png/jcr:content/renditions/fb_r_w.webp",
                            Price = 25000m,
                            ProductionYear = 2025,
                            Transmission = 0,
                            TrunkCapacity = 30.0,
                            VehicleType = 2
                        },
                        new
                        {
                            Id = 10,
                            Acceleration = 2.6000000000000001,
                            Availability = true,
                            BodyType = 4,
                            Brand = "CBR1000RR-R Fireblade",
                            Drivetrain = 0,
                            EngineCapacity = 2.0,
                            FuelType = 4,
                            MaxSpeed = 450.0,
                            Mileage = 100.0,
                            Model = " SP Carbon Edition",
                            PictureURL = "https://www.honda.pl/content/dam/central/motorcycles/colour-picker/supersports/cbr1000rr-r/cbr1000rr-r_sp_carbon_2024/nh-c33p_mattepearlmorionblack/24YM_CBR1000RR-R_FIREBLADE_Studio_MAT_PEARL_MORION_BLACK_SP_Carbon_Edition_RHS.png/jcr:content/renditions/fb_r_w.webp",
                            Price = 25000m,
                            ProductionYear = 2025,
                            Transmission = 0,
                            TrunkCapacity = 45.0,
                            VehicleType = 2
                        },
                        new
                        {
                            Id = 11,
                            Acceleration = 8.1999999999999993,
                            Availability = true,
                            BodyType = 2,
                            Brand = "Toyota",
                            Drivetrain = 0,
                            EngineCapacity = 1.8,
                            FuelType = 3,
                            MaxSpeed = 200.0,
                            Mileage = 10000.0,
                            Model = "Corolla",
                            PictureURL = "https://www.superauto.pl/file/2611717/3bbd42a17213074b29b6018891029b448b4a8aff-2-767x511",
                            Price = 90000m,
                            ProductionYear = 2023,
                            Transmission = 1,
                            TrunkCapacity = 470.0,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = 12,
                            Acceleration = 9.0,
                            Availability = true,
                            BodyType = 1,
                            Brand = "Volkswagen",
                            Drivetrain = 0,
                            EngineCapacity = 1.5,
                            FuelType = 0,
                            MaxSpeed = 210.0,
                            Mileage = 20000.0,
                            Model = "Golf",
                            PictureURL = "https://www.superauto.pl/file/2611717/3bbd42a17213074b29b6018891029b448b4a8aff-2-767x511",
                            Price = 80000m,
                            ProductionYear = 2022,
                            Transmission = 0,
                            TrunkCapacity = 380.0,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = 13,
                            Acceleration = 7.5,
                            Availability = true,
                            BodyType = 2,
                            Brand = "Audi",
                            Drivetrain = 2,
                            EngineCapacity = 2.0,
                            FuelType = 1,
                            MaxSpeed = 240.0,
                            Mileage = 15000.0,
                            Model = "A4",
                            PictureURL = "https://www.superauto.pl/file/2611717/3bbd42a17213074b29b6018891029b448b4a8aff-2-767x511",
                            Price = 170000m,
                            ProductionYear = 2021,
                            Transmission = 1,
                            TrunkCapacity = 480.0,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = 14,
                            Acceleration = 8.8000000000000007,
                            Availability = true,
                            BodyType = 3,
                            Brand = "Skoda",
                            Drivetrain = 0,
                            EngineCapacity = 1.6000000000000001,
                            FuelType = 0,
                            MaxSpeed = 220.0,
                            Mileage = 5000.0,
                            Model = "Octavia",
                            PictureURL = "https://www.superauto.pl/file/2611717/3bbd42a17213074b29b6018891029b448b4a8aff-2-767x511",
                            Price = 95000m,
                            ProductionYear = 2024,
                            Transmission = 1,
                            TrunkCapacity = 600.0,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = 15,
                            Acceleration = 9.5,
                            Availability = true,
                            BodyType = 1,
                            Brand = "Peugeot",
                            Drivetrain = 0,
                            EngineCapacity = 1.2,
                            FuelType = 0,
                            MaxSpeed = 205.0,
                            Mileage = 12000.0,
                            Model = "308",
                            PictureURL = "https://www.superauto.pl/file/2611717/3bbd42a17213074b29b6018891029b448b4a8aff-2-767x511",
                            Price = 70000m,
                            ProductionYear = 2023,
                            Transmission = 0,
                            TrunkCapacity = 340.0,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = 16,
                            Acceleration = 9.0,
                            Availability = true,
                            BodyType = 0,
                            Brand = "Kia",
                            Drivetrain = 2,
                            EngineCapacity = 1.6000000000000001,
                            FuelType = 1,
                            MaxSpeed = 210.0,
                            Mileage = 8000.0,
                            Model = "Sportage",
                            PictureURL = "https://www.superauto.pl/file/2611717/3bbd42a17213074b29b6018891029b448b4a8aff-2-767x511",
                            Price = 130000m,
                            ProductionYear = 2024,
                            Transmission = 1,
                            TrunkCapacity = 520.0,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = 17,
                            Acceleration = 6.7999999999999998,
                            Availability = true,
                            BodyType = 0,
                            Brand = "Volvo",
                            Drivetrain = 2,
                            EngineCapacity = 2.0,
                            FuelType = 0,
                            MaxSpeed = 230.0,
                            Mileage = 0.0,
                            Model = "XC60",
                            PictureURL = "https://www.superauto.pl/file/2611717/3bbd42a17213074b29b6018891029b448b4a8aff-2-767x511",
                            Price = 240000m,
                            ProductionYear = 2025,
                            Transmission = 1,
                            TrunkCapacity = 505.0,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = 18,
                            Acceleration = 8.1999999999999993,
                            Availability = true,
                            BodyType = 0,
                            Brand = "Mazda",
                            Drivetrain = 2,
                            EngineCapacity = 2.5,
                            FuelType = 0,
                            MaxSpeed = 220.0,
                            Mileage = 10000.0,
                            Model = "CX-5",
                            PictureURL = "https://www.superauto.pl/file/2611717/3bbd42a17213074b29b6018891029b448b4a8aff-2-767x511",
                            Price = 140000m,
                            ProductionYear = 2023,
                            Transmission = 1,
                            TrunkCapacity = 510.0,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = 19,
                            Acceleration = 9.5,
                            Availability = true,
                            BodyType = 0,
                            Brand = "Nissan",
                            Drivetrain = 0,
                            EngineCapacity = 1.3,
                            FuelType = 0,
                            MaxSpeed = 210.0,
                            Mileage = 5000.0,
                            Model = "Qashqai",
                            PictureURL = "https://www.superauto.pl/file/2611717/3bbd42a17213074b29b6018891029b448b4a8aff-2-767x511",
                            Price = 110000m,
                            ProductionYear = 2024,
                            Transmission = 1,
                            TrunkCapacity = 430.0,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = 20,
                            Acceleration = 8.5,
                            Availability = true,
                            BodyType = 0,
                            Brand = "Hyundai",
                            Drivetrain = 2,
                            EngineCapacity = 1.6000000000000001,
                            FuelType = 3,
                            MaxSpeed = 220.0,
                            Mileage = 0.0,
                            Model = "Tucson",
                            PictureURL = "https://www.superauto.pl/file/2611717/3bbd42a17213074b29b6018891029b448b4a8aff-2-767x511",
                            Price = 150000m,
                            ProductionYear = 2025,
                            Transmission = 1,
                            TrunkCapacity = 540.0,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = 21,
                            Acceleration = 4.5,
                            Availability = true,
                            BodyType = 3,
                            Brand = "Ford",
                            Drivetrain = 1,
                            EngineCapacity = 5.0,
                            FuelType = 0,
                            MaxSpeed = 250.0,
                            Mileage = 0.0,
                            Model = "Mustang",
                            PictureURL = "https://www.superauto.pl/file/2611717/3bbd42a17213074b29b6018891029b448b4a8aff-2-767x511",
                            Price = 300000m,
                            ProductionYear = 2024,
                            Transmission = 1,
                            TrunkCapacity = 380.0,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = 22,
                            Acceleration = 4.2000000000000002,
                            Availability = true,
                            BodyType = 1,
                            Brand = "Chevrolet",
                            Drivetrain = 1,
                            EngineCapacity = 6.2000000000000002,
                            FuelType = 0,
                            MaxSpeed = 260.0,
                            Mileage = 5000.0,
                            Model = "Camaro",
                            PictureURL = "https://www.superauto.pl/file/2611717/3bbd42a17213074b29b6018891029b448b4a8aff-2-767x511",
                            Price = 280000m,
                            ProductionYear = 2023,
                            Transmission = 1,
                            TrunkCapacity = 340.0,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = 23,
                            Acceleration = 3.1000000000000001,
                            Availability = true,
                            BodyType = 2,
                            Brand = "Tesla",
                            Drivetrain = 2,
                            EngineCapacity = 0.0,
                            FuelType = 2,
                            MaxSpeed = 260.0,
                            Mileage = 0.0,
                            Model = "Model 3",
                            PictureURL = "https://www.superauto.pl/file/2611717/3bbd42a17213074b29b6018891029b448b4a8aff-2-767x511",
                            Price = 220000m,
                            ProductionYear = 2024,
                            Transmission = 1,
                            TrunkCapacity = 425.0,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = 24,
                            Acceleration = 3.5,
                            Availability = true,
                            BodyType = 1,
                            Brand = "Porsche",
                            Drivetrain = 1,
                            EngineCapacity = 3.0,
                            FuelType = 0,
                            MaxSpeed = 300.0,
                            Mileage = 0.0,
                            Model = "911",
                            PictureURL = "https://www.superauto.pl/file/2611717/3bbd42a17213074b29b6018891029b448b4a8aff-2-767x511",
                            Price = 500000m,
                            ProductionYear = 2025,
                            Transmission = 1,
                            TrunkCapacity = 280.0,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = 25,
                            Acceleration = 12.0,
                            Availability = true,
                            BodyType = 1,
                            Brand = "Fiat",
                            Drivetrain = 0,
                            EngineCapacity = 1.2,
                            FuelType = 0,
                            MaxSpeed = 180.0,
                            Mileage = 15000.0,
                            Model = "500",
                            PictureURL = "https://www.superauto.pl/file/2611717/3bbd42a17213074b29b6018891029b448b4a8aff-2-767x511",
                            Price = 60000m,
                            ProductionYear = 2023,
                            Transmission = 0,
                            TrunkCapacity = 185.0,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = 26,
                            Acceleration = 8.0,
                            Availability = true,
                            BodyType = 0,
                            Brand = "Jeep",
                            Drivetrain = 2,
                            EngineCapacity = 2.0,
                            FuelType = 0,
                            MaxSpeed = 200.0,
                            Mileage = 0.0,
                            Model = "Wrangler",
                            PictureURL = "https://www.superauto.pl/file/2611717/3bbd42a17213074b29b6018891029b448b4a8aff-2-767x511",
                            Price = 200000m,
                            ProductionYear = 2024,
                            Transmission = 1,
                            TrunkCapacity = 270.0,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = 27,
                            Acceleration = 6.5,
                            Availability = true,
                            BodyType = 0,
                            Brand = "Land Rover",
                            Drivetrain = 2,
                            EngineCapacity = 3.0,
                            FuelType = 1,
                            MaxSpeed = 220.0,
                            Mileage = 0.0,
                            Model = "Defender",
                            PictureURL = "https://www.superauto.pl/file/2611717/3bbd42a17213074b29b6018891029b448b4a8aff-2-767x511",
                            Price = 350000m,
                            ProductionYear = 2025,
                            Transmission = 1,
                            TrunkCapacity = 550.0,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = 28,
                            Acceleration = 8.0,
                            Availability = true,
                            BodyType = 3,
                            Brand = "Subaru",
                            Drivetrain = 2,
                            EngineCapacity = 2.5,
                            FuelType = 0,
                            MaxSpeed = 210.0,
                            Mileage = 5000.0,
                            Model = "Outback",
                            PictureURL = "https://www.superauto.pl/file/2611717/3bbd42a17213074b29b6018891029b448b4a8aff-2-767x511",
                            Price = 160000m,
                            ProductionYear = 2024,
                            Transmission = 1,
                            TrunkCapacity = 580.0,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = 29,
                            Acceleration = 7.0,
                            Availability = true,
                            BodyType = 0,
                            Brand = "Lexus",
                            Drivetrain = 2,
                            EngineCapacity = 3.5,
                            FuelType = 3,
                            MaxSpeed = 230.0,
                            Mileage = 0.0,
                            Model = "RX",
                            PictureURL = "https://www.superauto.pl/file/2611717/3bbd42a17213074b29b6018891029b448b4a8aff-2-767x511",
                            Price = 300000m,
                            ProductionYear = 2025,
                            Transmission = 1,
                            TrunkCapacity = 520.0,
                            VehicleType = 0
                        },
                        new
                        {
                            Id = 30,
                            Acceleration = 8.0,
                            Availability = true,
                            BodyType = 2,
                            Brand = "Honda",
                            Drivetrain = 0,
                            EngineCapacity = 1.5,
                            FuelType = 0,
                            MaxSpeed = 210.0,
                            Mileage = 0.0,
                            Model = "Civic",
                            PictureURL = "https://www.superauto.pl/file/2611717/3bbd42a17213074b29b6018891029b448b4a8aff-2-767x511",
                            Price = 100000m,
                            ProductionYear = 2024,
                            Transmission = 1,
                            TrunkCapacity = 420.0,
                            VehicleType = 0
                        });
                });

            modelBuilder.Entity("Varico.EF.Models.Users", b =>
                {
                    b.HasOne("Varico.EF.Models.Vehicle", "Car")
                        .WithMany()
                        .HasForeignKey("CarId");

                    b.Navigation("Car");
                });

            modelBuilder.Entity("Varico.EF.Models.Vehicle", b =>
                {
                    b.HasOne("Varico.EF.Models.Users", "ReservedBy")
                        .WithMany()
                        .HasForeignKey("ReservedById");

                    b.Navigation("ReservedBy");
                });
#pragma warning restore 612, 618
        }
    }
}
